spring:
  datasource:
    url: jdbc:mysql://192.168.2.104:3306/sayagain
  mvc:
    static-path-pattern: /sayagain/**
springdoc:
  swagger-ui:
    url: /sayagain/sayagain-api-specification.yml
server:
  servlet:
    context-path: /sayagain
